### ISSUE TITLE
Peer to Peer Code Review 

### ISSUE THREAD

**Issue by benjp009** [Mosams/Personal-Portfolio#12]
# 👋  @Mosams 

### Great work on your portfolio,

- [ ] Try to fix the scrolling of the popup if the popup is bigger than the phone size 
- [ ] On the project's description would have more padding to improve user's experience. 
- [ ] Work on the padding of the button to make it centered 
- [ ] Try to limit the images, so they are not too big - `max-width: 50% `(for example)

**Comment by topeogunleye** [comment]
@Mosams , 
Your project looks great but I have some suggestions: 

- [x] On Desktop, You can give your project images container a max-width of 45%, and your text container a max-width of 50%. Then apply display of flex and justify: space between on their container(project card).

**Comment by Mosams** [comment]
Thanks for ur contributions towards improving my UX
