### ISSUE TITLE
Portfolio Website Feedback

### ISSUE THREAD

**Issue by AmaduKamara** [Mosams/Personal-Portfolio#6]
## Feedback and Changes Required ♻️

So far your work is looking great Sam.
There are a few changes we recommend you take a look at to make your design look much better.

- Make the logo get in a little bit just as the nav items. I suggest you give a 10% padding left and right for the header
- Adjust the height of the work cards to match the Figma design
- The transition for the card should be applied to the card image when you hover the image
- Adjust the button in the card to not wrap. I don't know if you gave it a fixed width.

But you're doing great in your design so far.
Keep it up bro.

**Comment by Mosams** [comment]
Thank you for all your contributions towards improving my site. I have implemented the suggested changes
